config:
  node_agent: 'docker-compose'
  deploy_template: '.sqa/docker-compose.yml'
  project_repos:
    jenkins-pipeline-library:
      repo: 'https://github.com/WORSICA/jenkins-pipeline-library.git'
      branch: docker-compose
      dockerhub: worsica/jenkins-pipeline-library
      dockertag: latest

sqa-criteria:
  qc-doc:
    repos:
      jenkins-pipeline-library:
        container: ci_java
        when:
        -
          branch: master
          withCredentials:
            credentialsId: "indigobot-github-token"
            variable: "GITHUB_TOKEN"
        commands:
          - 'cd /jenkins-pipeline-library && groovydoc -d docs vars/*.groovy'
          - 'cd /jenkins-pipeline-library && git config -l'
          - 'cd /jenkins-pipeline-library && git remote set-url origin "https://indigobot:${GITHUB_TOKEN}@github.com/indigo-dc/jenkins-pipeline-library"'
          - 'cd /jenkins-pipeline-library && gh-pages-multi deploy'
      jenkins-pipeline-library-docs:
        container: ci_java
        withCredentials:
          string:
            credentialsId: "indigobot-github-token"
            variable: "GITHUB_TOKEN"
        commands:
          - 'cd /jenkins-pipeline-library-docs && groovydoc -d ${env.GIT_BRANCH} vars/*.groovy'
          - 'cd /jenkins-pipeline-library-docs && git remote set-url origin "https://indigobot:${GITHUB_TOKEN}@github.com/indigo-dc/jenkins-pipeline-library"'
          - 'cd /jenkins-pipeline-library-docs && gh-pages-multi deploy -s ${env.GIT_BRANCH} -t ${env.GIT_BRANCH}'

timeout: 600
