config:
  node_agent: 'docker-compose'
  deploy_template: '.sqa/docker-compose.yml'
  project_repos:
    jenkins-pipeline-library:
      repo: 'https://github.com/WORSICA/jenkins-pipeline-library.git'
      branch: master
      dockerhub: worsica/jenkins-pipeline-library
      dockertag: latest
    jenkins-pipeline-library-docs:
      repo: 'https://github.com/WORSICA/jenkins-pipeline-library.git'
      branch: release/2.0.0-docs
      dockerhub: worsica/jenkins-pipeline-library-docs
      dockertag: latest

sqa-criteria:
  qc-doc:
    repos:
      jenkins-pipeline-library:
        container: ci_java
        withCredentials:
          string:
            credentialsId: "samuelbernardolip-github-token"
            variable: "GITHUB_TOKEN"
        environment:
          GITHUB_TOKEN: "${GITHUB_TOKEN}"
        commands:
          - 'cd /jenkins-pipeline-library && groovydoc -d docs vars/*.groovy'
          - 'cd /jenkins-pipeline-library && git config -l'
          - 'cd /jenkins-pipeline-library && git remote set-url origin "https://samuelbernardolip:${GITHUB_TOKEN}@github.com/WORSICA/jenkins-pipeline-library"'
          - 'cd /jenkins-pipeline-library && gh-pages-multi deploy'
      jenkins-pipeline-library-docs:
        container: ci_java
        withCredentials:
          string:
            credentialsId: "samuelbernardolip-github-token"
            variable: "GITHUB_TOKEN"
        environment:
          GITHUB_TOKEN: "${GITHUB_TOKEN}"
          GIT_BRANCH: "${GIT_BRANCH}"
        commands:
          - 'cd /jenkins-pipeline-library-docs && groovydoc -d ${GIT_BRANCH} vars/*.groovy'
          - 'cd /jenkins-pipeline-library-docs && git remote set-url origin "https://samuelbernardolip:${GITHUB_TOKEN}@github.com/WORSICA/jenkins-pipeline-library"'
          - 'cd /jenkins-pipeline-library-docs && gh-pages-multi deploy -s ${GIT_BRANCH} -t ${GIT_BRANCH}'

timeout: 600
