version: "3.7"

services:
  ci_java:
    build:
      context: .
      dockerfile: Dockerfile
    image: "worsica/jenkins-pipeline-library:ci_java"
    container_name: "ci_java"
    hostname: "ci_java"
    volumes:
     - type: bind
       source: ./jenkins-pipeline-library
       target: /jenkins-pipeline-library
     - type: bind
       source: ./jenkins-pipeline-library-docs
       target: /jenkins-pipeline-library-docs
